package com.faceclaw.sdk;

import android.os.*;
import com.faceclaw.sdk.ipc.IFaceclawHostSession;
import org.json.JSONObject;
import java.util.*;

/** Authenticated application-side session. Thread-safe; callbacks are marshalled by the service. */
public final class FaceclawSession {
 interface Callback {void onSnapshot(HostSnapshot snapshot);void onControl(ControlEvent event);void onInput(RenderSurface surface,FaceclawInputEvent event);void onCreditWithoutRenderer(RenderSurface surface,RenderCredit credit);void onOutcome(FrameOutcome outcome);}
 private IFaceclawHostSession host;private final Callback callback;private final Map<String,RenderSurface> surfaces=new HashMap<>();private final ResourceRegistry resources;private long nextFrame=1,nextContent=1;private boolean closed,connected=true;
 FaceclawSession(IFaceclawHostSession host,Callback callback){this.host=host;this.callback=callback;resources=new ResourceRegistry(this);surfaces.put("window",new RenderSurface(this,"window"));}
 public synchronized RenderSurface windowSurface(){return surfaces.get("window");}
 public synchronized RenderSurface extensionSurface(String feature){return surfaces.computeIfAbsent("extension:"+feature,id->new RenderSurface(this,id));}
 public ResourceRegistry resources(){return resources;}
 synchronized void invalidateAll(){for(RenderSurface surface:surfaces.values())surface.invalidate(InvalidateReason.STATE);}
 public synchronized long nextClientFrameId(){return nextFrame++;}public synchronized long nextContentVersion(){return nextContent++;}
 public synchronized void setRestorationToken(byte[] value){if(value==null||value.length>4096)throw new IllegalArgumentException("Restoration token exceeds 4 KiB");Bundle b=new Bundle();b.putByteArray("value",value.clone());sendControlBundle("restoration-token",b);}
 synchronized void attach(IFaceclawHostSession next){if(closed)throw new IllegalStateException("Session is closed");host=next;connected=true;}
 synchronized void detach(){if(closed)return;connected=false;host=null;for(RenderSurface surface:surfaces.values())surface.suspend();}
 synchronized void applySnapshot(Bundle wire){if(closed||!connected)return;HostSnapshot snapshot=new HostSnapshot(wire);if(snapshot.protocolMajor!=Protocol.VERSION){close();return;}if(snapshot.surfaces.isEmpty()){RenderSurface window=surfaces.get("window");if(snapshot.windowOpen)window.configure(snapshot.windowWidth,snapshot.windowHeight,snapshot.windowGeneration,snapshot.windowVisible,snapshot.screenOn);}else for(SurfaceSnapshot state:snapshot.surfaces){RenderSurface surface="window".equals(state.id)?surfaces.get("window"):state.id.startsWith("extension:")?extensionSurface(state.id.substring(10)):null;if(surface!=null)surface.configure(state.width,state.height,state.generation,state.visible,state.screenOn);}callback.onSnapshot(snapshot);resources.replay();for(RenderSurface surface:surfaces.values())surface.replayScene();}
 synchronized void applyControl(Bundle wire){if(closed)return;String type=wire.getString("type","");JSONObject data;try{data=Protocol.json(wire);}catch(Exception ignored){return;}
  try{
   if(type.equals("open")||type.equals("resize")){RenderSurface window=surfaces.get("window");window.configure(data.getInt("width"),data.getInt("height"),data.getLong("generation"),data.optBoolean("visible",window.visible()),data.optBoolean("screenOn",true));window.replayScene();}
   else if(type.equals("visibility"))surfaces.get("window").setVisibility(data.optBoolean("visible"),data.optBoolean("screenOn",true));
   else if(type.equals("close"))surfaces.get("window").setVisibility(false,false);
   else if(type.equals("extension-surface")){String feature=data.getString("feature");RenderSurface surface=extensionSurface(feature);String action=data.getString("type");if(action.equals("open")||action.equals("resize")){surface.configure(data.getInt("width"),data.getInt("height"),data.getLong("generation"),data.optBoolean("visible",true),data.optBoolean("screenOn",true));surface.replayScene();}else if(action.equals("visibility"))surface.setVisibility(data.optBoolean("visible"),data.optBoolean("screenOn",true));else if(action.equals("close")){surface.close();surfaces.remove("extension:"+feature);}}
   if(type.equals("input"))callback.onInput(surfaces.get("window"),new FaceclawInputEvent(data));
   else callback.onControl(new ControlEvent(type,data));
  }catch(Exception ignored){}
 }
 synchronized void grant(Bundle wire){RenderSurface surface=surfaces.get(wire.getString("surfaceId"));if(surface==null)return;RenderCredit credit=new RenderCredit(surface.id(),wire.getLong("generation"),wire.getLong("creditId"),wire.getLong("targetPresentationTimeNanos"),wire.getInt("maxDamageRects",Protocol.MAX_DAMAGE_RECTS),wire.getString("traceId",""));boolean notify=!surface.hasRenderer();surface.grant(credit);if(notify)callback.onCreditWithoutRenderer(surface,credit);}
 synchronized void released(String id,long generation,int slot,long sequence){RenderSurface surface=surfaces.get(id);if(surface!=null&&surface.generation()==generation)surface.release(slot,sequence);}
 synchronized void outcome(Bundle wire){try{FrameOutcome.Status status=FrameOutcome.Status.valueOf(wire.getString("status","CANCELLED"));callback.onOutcome(new FrameOutcome(wire.getString("surfaceId",""),wire.getLong("clientFrameId"),wire.getLong("contentVersion"),status,wire.getString("traceId",""),wire.getString("diagnostic",""),wire.getBoolean("metadataDropped")));}catch(Exception ignored){}}
 synchronized void registerSurface(RenderSurface surface,ArrayList<SharedMemory> memories){IFaceclawHostSession current=host;if(!connected||current==null)return;try{Bundle b=new Bundle();b.putString("surfaceId",surface.id());b.putLong("generation",surface.generation());b.putInt("width",surface.width());b.putInt("height",surface.height());b.putParcelableArrayList("buffers",memories);current.registerSurface(b);}catch(RemoteException e){detach();}}
 synchronized void unregisterSurface(RenderSurface surface){IFaceclawHostSession current=host;if(!connected||current==null)return;try{current.unregisterSurface(surface.id(),surface.generation());}catch(RemoteException ignored){detach();}}
 synchronized void requestRender(RenderSurface surface,InvalidateReason reason){IFaceclawHostSession current=host;if(closed||!connected||current==null)return;try{current.requestRender(surface.id(),surface.generation(),reason.ordinal());}catch(RemoteException e){detach();}}
 synchronized void submitFrame(RenderSurface surface,FrameLease lease,FrameMetadata metadata){IFaceclawHostSession current=host;if(!connected||current==null){surface.release(lease.slotId,lease.sequence);return;}try{Bundle b=new Bundle();b.putString("surfaceId",surface.id());b.putLong("generation",surface.generation());b.putInt("slotId",lease.slotId);b.putLong("sequence",lease.sequence);b.putLong("creditId",lease.credit.creditId);b.putLong("clientFrameId",metadata.clientFrameId);b.putLong("contentVersion",metadata.contentVersion);b.putBoolean("requestNextFrame",metadata.requestNextFrame);b.putString("traceId",metadata.traceId);List<DamageRect> damage=metadata.damage.isEmpty()?Collections.singletonList(new DamageRect(0,0,surface.width(),surface.height())):metadata.damage;int[] rects=new int[damage.size()*4];for(int i=0;i<damage.size();i++){DamageRect r=damage.get(i);rects[i*4]=r.x;rects[i*4+1]=r.y;rects[i*4+2]=r.width;rects[i*4+3]=r.height;}b.putIntArray("damage",rects);if(metadata.draws!=null)b.putByteArray("draws",metadata.draws.encode());current.submitFrame(b);}catch(Exception e){surface.release(lease.slotId,lease.sequence);detach();}}
 synchronized boolean sendControl(String type,JSONObject json){IFaceclawHostSession current=host;if(closed||!connected||current==null)return false;try{current.sendControl(Protocol.control(type,json));return true;}catch(Exception e){detach();return false;}}
 private synchronized void sendControlBundle(String type,Bundle data){IFaceclawHostSession current=host;if(!connected||current==null)return;try{data.putString("type",type);current.sendControl(data);}catch(Exception e){detach();}}
 synchronized void registerResource(ResourceHandle handle,byte[] pixels){IFaceclawHostSession current=host;if(!connected||current==null)return;try{Bundle b=new Bundle();b.putInt("id",handle.id);b.putString("type",handle.type.name());b.putInt("width",handle.width);b.putInt("height",handle.height);b.putString("sha256",handle.sha256);b.putByteArray("pixels",pixels);current.registerResource(b);}catch(Exception e){detach();}}
 synchronized boolean commitScene(RenderSurface surface,SceneTransaction transaction){IFaceclawHostSession current=host;if(closed||!connected||current==null||surface.generation()==0)return false;try{current.commitScene(transaction.wire(surface.id(),surface.generation()));return true;}catch(Exception e){detach();return false;}}
 public synchronized void close(){if(closed)return;closed=true;connected=false;IFaceclawHostSession current=host;host=null;for(RenderSurface surface:surfaces.values())surface.closeFromSession();surfaces.clear();try{if(current!=null){Bundle b=new Bundle();b.putString("reason",DisconnectInfo.Reason.HOST_STOPPED.name());current.close(b);}}catch(Exception ignored){}}
 synchronized void closeSilently(){if(closed)return;closed=true;connected=false;host=null;for(RenderSurface surface:surfaces.values())surface.closeFromSession();surfaces.clear();}
}
